name: Deploy multi docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sfrumkin/multi-client ./client
      - run: docker build -t sfrumkin/multi-nginx ./nginx
      - run: docker build -t sfrumkin/multi-server ./server
      - run: docker build -t sfrumkin/multi-worker ./worker
      - run: docker push sfrumkin/multi-client
      - run: docker push sfrumkin/multi-nginx
      - run: docker push sfrumkin/multi-server
      - run: docker push sfrumkin/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-115016178629
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
